language: php
php:
  - 7.1.9
services:
  - docker
  - rabbitmq

addons:
  apt:
    packages:
      - rabbitmq-server  

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin      

script:
  - docker build -t rajdeepdas/email-notifier .
  - docker push rajdeepdas/email-notifier
